In [1]:
import cv2
import numpy as np

In [2]:
flag = cv2.imread('flag.png')
lemur = cv2.imread('flag.png')

In [3]:
for _ in flag:
    print(_)

[[247 243 247]
 [ 70 240  70]
 [ 98 160 247]
 ...
 [ 34  95  61]
 [189  97 137]
 [ 78 124 246]]
[[233  89 157]
 [ 60  88  32]
 [101 184  52]
 ...
 [ 45  72 130]
 [226 118 120]
 [ 98 152  49]]
[[ 50 192 208]
 [ 36 202 231]
 [110  32  75]
 ...
 [ 99  15  21]
 [165  41 227]
 [ 27 188 187]]
[[161  67   6]
 [100 142  41]
 [ 52  12  19]
 ...
 [ 58 179  10]
 [ 42 169   4]
 [246  23 100]]
[[  0 174 135]
 [ 31  64 147]
 [ 31  47 173]
 ...
 [208 132 240]
 [174 176  34]
 [ 91  82  93]]
[[235  31  50]
 [104  83  39]
 [102 129 162]
 ...
 [190 116 202]
 [189 170  85]
 [217 155 149]]
[[ 87 144 230]
 [238  52 166]
 [222  25 230]
 ...
 [225 108  13]
 [ 78 156 212]
 [200  75  82]]
[[ 23  97 156]
 [ 96  72 197]
 [125  25 174]
 ...
 [  2  59 239]
 [ 62 183 250]
 [193  91   1]]
[[191 230  78]
 [156  82   7]
 [178 208 139]
 ...
 [ 86 113  48]
 [167 184 193]
 [160 222   5]]
[[ 83  59 220]
 [ 78 116  82]
 [110 103 195]
 ...
 [ 88 235  48]
 [250  37 220]
 [ 84 231 155]]
[[225 159 107]
 [ 70 150 109]
 [ 72  28 